# Generated by Django 2.2 on 2020-03-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ssh_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='ssh秘钥名')),
                ('ssh_rsa', models.CharField(max_length=2048, verbose_name='ssh秘钥')),
                ('ssh_user_name', models.CharField(max_length=32, verbose_name='ssh登录用户名')),
                ('ssh_password', models.CharField(max_length=32, verbose_name='ssh密码')),
            ],
            options={
                'verbose_name_plural': '密码表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '标签表',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('ssh_key', models.ManyToManyField(to='hello.ssh_key')),
                ('tag', models.ManyToManyField(to='hello.Tag')),
            ],
            options={
                'verbose_name_plural': '资产表',
            },
        ),
    ]
